# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b697dc614b7800a90fd3e1f5e977032e"
name = "upsell"
handle = "upsell-191"
application_url = "https://fd12-2401-4900-1c80-459e-2fef-cab7-3ce9-dec3.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nintestdev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fd12-2401-4900-1c80-459e-2fef-cab7-3ce9-dec3.ngrok-free.app/auth/callback",
  "https://fd12-2401-4900-1c80-459e-2fef-cab7-3ce9-dec3.ngrok-free.app/auth/shopify/callback",
  "https://fd12-2401-4900-1c80-459e-2fef-cab7-3ce9-dec3.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
